services:
  - type: web
    name: pdf-chat-analyser
    env: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: mkdir -p temp && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROK_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
